# workaround for https://github.com/jitpack/jitpack.io/issues/1887

jdk:
  - oraclejdk8
before_install:
   - wget -q https://repo.maven.apache.org/maven2/org/scala-sbt/sbt-launch/1.2.8/sbt-launch-1.2.8.jar
install:
   - java -jar sbt-launch-1.2.8.jar +publishM2